name: Maven Central Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: Tag Version (add prefix v)
        required: true

jobs:
  build-publish:
    name: Build & maven publish
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout for ${{ github.event.inputs.version }}
        uses: actions/checkout@v3

        # DO NOT USE CONTAINER, else gpg sign step will fail
      - name: Set up Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          # Set this in pom.xml or in parent/pom.xml
          server-id: ossrh-ajaxer-org
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Building & Deploying ${{ github.event.inputs.version }}
        run: mvn clean deploy -P release --no-transfer-progress -e
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

  tag-release:
    needs: build-publish
    name: Git tag & release
    runs-on: ubuntu-latest
    container: ershakiransari/jdk:8-mvn3
    steps:
      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Code checkout for ${{ github.event.inputs.version }}
        uses: actions/checkout@v3

      - name: Building artifact for ${{ github.event.inputs.version }}
        run: mvn clean package --no-transfer-progress

      # Creating A Release
      - name: Creating Release ${{ github.event.inputs.version }}
        id: create_release
        uses: actions/create-release@v1
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Version ${{ github.event.inputs.version }}
          body: |
            - Build Number: ${{ github.run_number }}
            - Released on ${{ env.date_today }}
          draft: false
          prerelease: false
